var MasterList = {
  "genders": ["Male", "Female"],
  "Nationality": [
    "Afghan",
    "Albanian",
    "Algerian",
    "Andorran",
    "Angolan",
    "Antiguan",
    "Argentine",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "Bruneian",
    "Bulgarian",
    "Burkinabé",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comorian",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djiboutian",
    "Dominican",
    "Ecuadorian",
    "Egyptian",
    "Salvadoran",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Swazi",
    "Ethiopian",
    "Fijian",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinean",
    "Bissau-Guinean",
    "Guyanese",
    "Haitian",
    "Honduran",
    "Hungarian",
    "Icelandic",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "I-Kiribati",
    "Kuwaiti",
    "Kyrgyz",
    "Lao",
    "Latvian",
    "Lebanese",
    "Basotho",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monegasque",
    "Mongolian",
    "Montenegrin",
    "Moroccan",
    "Mozambican",
    "Burmese",
    "Namibian",
    "Nauruan",
    "Nepali",
    "Dutch",
    "New Zealander",
    "Nicaraguan",
    "Nigerien",
    "Nigerian",
    "North Korean",
    "Macedonian",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Palestinian",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Filipino",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Kittitian",
    "Saint Lucian",
    "Vincentian",
    "Samoan",
    "Sammarinese",
    "São Toméan",
    "Saudi",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "South Sudanese",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamese",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajikistani",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian",
    "Tunisian",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Emirati",
    "British",
    "American",
    "Uruguayan",
    "Uzbekistani",
    "Ni-Vanuatu",
    "Vatican",
    "Venezuelan",
    "Vietnamese",
    "Yemeni",
    "Zambian",
    "Zimbabwean",
  ],
  "zodiacs": [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],
  "religions": [
    "Christianity",
    "Islam",
    "Hinduism",
    "Buddhism",
    "Judaism",
    "Sikhism",
    "Baháʼí Faith",
    "Jainism",
    "Shinto",
    "Taoism",
    "Zoroastrianism",
    "Traditional African Religions",
    "Indigenous Religions",
    "Non-religious / Secular / Atheist / Agnostic",
  ],
  "casts": [
    "Brahmin",
    "Maratha",
    "Kunbi",
    "Mali",
    "Rajput",
    "Kayastha",
    "Jat",
    "Yadav",
    "Baniya",
    "Lingayat",
    "Reddy",
    "Nair",
    "Ezhava",
    "Chettiar",
    "Vokkaliga",
    "Gounder",
    "Patel",
    "Kamma",
    "Kurmi",
    "Dalit",
  ],
  "mother_tounge": [
    "Assamese",
    "Bengali",
    "Bodo",
    "Dogri",
    "Gujarati",
    "Hindi",
    "Kannada",
    "Kashmiri",
    "Konkani",
    "Maithili",
    "Malayalam",
    "Manipuri",
    "Marathi",
    "Nepali",
    "Odia",
    "Punjabi",
    "Sanskrit",
    "Santali",
    "Sindhi",
    "Tamil",
    "Telugu",
    "Urdu",
  ],
  "maratial_status": [
    "Single",
    "Married",
    "Divorced",
    "Widowed",
    "Separated",
    "Engaged",
    "In a Relationship",
  ],

  "blood_group": ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
  "hobbies": [
    "📖 Reading",
    "🎶 Music",
    "✈️ Traveling",
    "⚽️ Sports",
    "🧑🏻‍🍳 Cooking",
    "🎨 Painting",
    "📸 Photography",
    "🎮 Gaming",
    "🪴 Gardening",
    "📝 Writing",
  ],
  "Education": [
    "Below 10th",
    "10th Pass",
    "12th Pass",
    "ITI",
    "Diploma",
    "Undergraduate",
    "Graduate",
    "Postgraduate",
    "Doctorate",
    "Professional (CA/CS/ICWA)",
    "Other",
  ],
  "profession": [
    "IT Professional",
    "Healthcare Professional",
    "Teacher",
    "Business Person",
    "Government Employee",
    "Skilled Worker",
    "Self-Employed",
    "Student",
    "Other",
  ],
  "salary_range": [
    "Below ₹1 Lakh",
    "₹1 Lakh – ₹3 Lakh",
    "₹3 Lakh – ₹5 Lakh",
    "₹5 Lakh – ₹7 Lakh",
    "₹7 Lakh – ₹10 Lakh",
    "₹10 Lakh – ₹15 Lakh",
    "₹15 Lakh – ₹20 Lakh",
    "₹20 Lakh – ₹30 Lakh",
    "₹30 Lakh – ₹50 Lakh",
    "Above ₹50 Lakh",
  ],
  "familyTypes": ["Joint Family", "Nuclear Family", "Extended Family", "Other"],
  "familyValues": ["Traditional", "Moderate", "Liberal", "Other"],
  "familyStatus": [
    "Lower Class",
    "Middle Class",
    "Upper Middle Class",
    "Rich / Affluent",
  ],
  "dietPreference": ["Veg", "Non-Veg", "Vegan", "Eggetarian"],
  "smokingHabit": ["Never", "Occasionally", "Regularly"],
  "drinkingHabit": ["Never", "Socially", "Often"],
  "fitnessActivity": ["Not Active", "Occasionally", "Regularly"],
  "sleepPattern": ["Early Bird", "Night Owl", "Flexible"],
  "petFriendly": ["Yes", "No", "Maybe"],
  "travelPreference": ["Rarely", "Occasionally", "Frequently"],
  "dailyRoutine": ["Structured", "Flexible", "Spontaneous"],
};
